version: '3'

services:
  coordinator:
    build:
      context: ./presto-coordinator
      args:
        node_id: coordinator
    volumes:
        - "./conf/catalog:/usr/local/presto/etc/catalog"
    ports:
      - "9080:9080"
    container_name: "coordinator"

  worker0:
    build:
      context: ./presto-worker
      args:
        node_id: worker0
    volumes:
        - "./conf/catalog:/usr/local/presto/etc/catalog"
    container_name: "worker0"
    ports:
      - "9081:8081"
  worker1:
    build:
      context: ./presto-worker
      args:
        node_id: worker1
    volumes:
        - "./conf/catalog:/usr/local/presto/etc/catalog"
    container_name: "worker1"
    ports:
      - "9082:8081"
  worker2:
    build:
      context: ./presto-worker
      args:
        node_id: worker2
    volumes:
        - "./conf/catalog:/usr/local/presto/etc/catalog"
    container_name: "worker2"
    ports:
      - "9083:8081"
